# Generated by Django 4.2.30 on 2026-06-09 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BienModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "prix_unitaire_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("date_achat", models.DateField(blank=True, null=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_maintenance", "En maintenance"),
                            ("endommage", "Endommagé"),
                            ("archive", "Archivé"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "stock_bien",
            },
        ),
        migrations.CreateModel(
            name="MouvementStockModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée"),
                            ("sortie", "Sortie"),
                            ("reservation", "Réservation"),
                            ("annulation_reservation", "Annulation réservation"),
                            ("retour", "Retour"),
                        ],
                        max_length=25,
                    ),
                ),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_document",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.bienmodel",
                    ),
                ),
            ],
            options={
                "db_table": "stock_mouvement",
            },
        ),
        migrations.CreateModel(
            name="DisponibilitePeriodeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("est_reserve", models.BooleanField(default=False)),
                ("reservation_id", models.UUIDField(blank=True, null=True)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.bienmodel",
                    ),
                ),
            ],
            options={
                "db_table": "stock_disponibilite",
            },
        ),
        migrations.CreateModel(
            name="CategorieModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stock.categoriemodel",
                    ),
                ),
            ],
            options={
                "db_table": "stock_categorie",
            },
        ),
        migrations.AddField(
            model_name="bienmodel",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.categoriemodel",
            ),
        ),
    ]
