# Generated by Django 4.2.30 on 2026-08-14 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bien",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "prix_unitaire_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("devise", models.CharField(default="USD", max_length=3)),
                ("date_achat", models.DateField(blank=True, null=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_maintenance", "En maintenance"),
                            ("endommage", "Endommagé"),
                            ("archive", "Archivé"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biens_stock",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bien",
                "verbose_name_plural": "Biens",
                "db_table": "stock_bien",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée"),
                            ("sortie", "Sortie"),
                            ("reservation", "Réservation"),
                            ("annulation_reservation", "Annulation réservation"),
                            ("retour", "Retour"),
                        ],
                        max_length=25,
                    ),
                ),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_document",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.bien"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "db_table": "stock_mouvement",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="DisponibilitePeriode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("est_reserve", models.BooleanField(default=False)),
                ("reservation_id", models.UUIDField(blank=True, null=True)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.bien"
                    ),
                ),
            ],
            options={
                "verbose_name": "Période de disponibilité",
                "verbose_name_plural": "Périodes de disponibilité",
                "db_table": "stock_disponibilite",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories_stock",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stock.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "db_table": "stock_categorie",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="bien",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.categorie",
            ),
        ),
    ]
