# Generated by Django 4.2.30 on 2026-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienmodel",
            name="devise",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
