# Generated by Django 4.2.30 on 2026-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_bienmodel_devise"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienmodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="categoriemodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
