from abc import ABC, abstractmethod
from typing import Optional, List
from uuid import UUID
from administration.domain.entities.agence import Agence
from administration.domain.value_objects.code_agence import CodeAgence

class AgenceRepository(ABC):
    @abstractmethod
    def get(self, id: UUID) -> Optional[Agence]: ...
    @abstractmethod
    def get_by_code(self, code: CodeAgence) -> Optional[Agence]: ...
    @abstractmethod
    def get_by_nom(self, nom: str) -> Optional[Agence]: ...
    @abstractmethod
    def add(self, agence: Agence) -> None: ...
    @abstractmethod
    def update(self, agence: Agence) -> None: ...
    @abstractmethod
    def list_actives(self) -> List[Agence]: ...
    @abstractmethod
    def list_all(self) -> List[Agence]: ...