from abc import ABC, abstractmethod
from typing import Optional, List
from uuid import UUID
from administration.domain.entities.module_systeme import ModuleSysteme
from administration.domain.value_objects.code_module import CodeModule

class ModuleRepository(ABC):
    @abstractmethod
    def get(self, id: UUID) -> Optional[ModuleSysteme]: ...
    @abstractmethod
    def get_by_code(self, code: CodeModule) -> Optional[ModuleSysteme]: ...
    @abstractmethod
    def add(self, module: ModuleSysteme) -> None: ...
    @abstractmethod
    def update(self, module: ModuleSysteme) -> None: ...
    @abstractmethod
    def list_actifs(self) -> List[ModuleSysteme]: ...
    @abstractmethod
    def list_all(self) -> List[ModuleSysteme]: ...