# Generated by Django 4.2.30 on 2026-08-14 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technicien",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "cout_horaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Coût horaire",
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="techniciens_maintenance",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technicien",
                "verbose_name_plural": "Techniciens",
                "db_table": "maintenance_technicien",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="RegleMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("forfait", "Forfait"),
                            ("remise", "Remise"),
                            ("majoration", "Majoration"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valeur"
                    ),
                ),
                (
                    "duree_min",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Durée min (h)"
                    ),
                ),
                (
                    "duree_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée max (h)"
                    ),
                ),
                (
                    "periode_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Période début"
                    ),
                ),
                (
                    "periode_fin",
                    models.DateField(blank=True, null=True, verbose_name="Période fin"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regles_maintenance",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de maintenance",
                "verbose_name_plural": "Règles de maintenance",
                "db_table": "maintenance_regle_tarification",
                "ordering": ["periode_debut"],
            },
        ),
        migrations.CreateModel(
            name="PieceDetachee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Prix unitaire"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pieces_maintenance",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce détachée",
                "verbose_name_plural": "Pièces détachées",
                "db_table": "maintenance_piece",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bien_id",
                    models.UUIDField(verbose_name="ID du bien (référence externe)"),
                ),
                ("date_debut", models.DateTimeField(verbose_name="Début")),
                ("date_fin", models.DateTimeField(verbose_name="Fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "cout_main_oeuvre",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Coût main d'œuvre",
                    ),
                ),
                (
                    "cout_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Coût total",
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interventions_maintenance",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.technicien",
                        verbose_name="Technicien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
                "db_table": "maintenance_intervention",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="InterventionPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="maintenance.intervention",
                        verbose_name="Intervention",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.piecedetachee",
                        verbose_name="Pièce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce utilisée",
                "verbose_name_plural": "Pièces utilisées",
                "db_table": "maintenance_intervention_piece",
                "unique_together": {("intervention", "piece")},
            },
        ),
    ]
