# Generated by Django 4.2.30 on 2026-06-09 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PieceDetacheeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=200)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "maintenance_piece",
            },
        ),
        migrations.CreateModel(
            name="TechnicienModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "cout_horaire",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
            ],
            options={
                "db_table": "maintenance_technicien",
            },
        ),
        migrations.CreateModel(
            name="InterventionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bien_id", models.UUIDField()),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                (
                    "cout_main_oeuvre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cout_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.technicienmodel",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_intervention",
            },
        ),
        migrations.CreateModel(
            name="InterventionPieceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.interventionmodel",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.piecedetacheemodel",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_intervention_piece",
                "unique_together": {("intervention", "piece")},
            },
        ),
    ]
