# Generated by Django 4.2.30 on 2026-06-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interventionpiecemodel",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pieces",
                to="maintenance.interventionmodel",
            ),
        ),
    ]
