# Generated by Django 4.2.30 on 2026-06-26 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_alter_interventionpiecemodel_intervention"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegleMaintenanceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agence_id", models.UUIDField(db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("forfait", "Forfait"),
                            ("remise", "Remise"),
                            ("majoration", "Majoration"),
                        ],
                        max_length=10,
                    ),
                ),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duree_min", models.PositiveIntegerField(default=0)),
                ("duree_max", models.PositiveIntegerField(blank=True, null=True)),
                ("periode_debut", models.DateField(blank=True, null=True)),
                ("periode_fin", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "maintenance_regle_tarification",
            },
        ),
    ]
