# Generated by Django 4.2.30 on 2026-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_reglemaintenancemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="interventionmodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="piecedetacheemodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="technicienmodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
