# Generated by Django 4.2.30 on 2026-08-14 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administration", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "matricule",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Matricule"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de famille"),
                ),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                ("date_embauche", models.DateField(verbose_name="Date d'embauche")),
                (
                    "taux_horaire",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Taux horaire"
                    ),
                ),
                (
                    "poste",
                    models.CharField(max_length=100, verbose_name="Poste occupé"),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Est actif"),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employes",
                        to="administration.agencemodel",
                        verbose_name="Agence de rattachement",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="Rôles (groupes)"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employe_rh",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "db_table": "rh_employe",
                "ordering": ["matricule"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nom du rôle"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="Liste des codes de permissions métier (ex: ['view_employe', 'add_pointage'])",
                        verbose_name="Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle métier",
                "verbose_name_plural": "Rôles métier",
                "db_table": "rh_role",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("date_evaluation", models.DateField(verbose_name="Date d'évaluation")),
                (
                    "note",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Note de 0.0 à 10.0",
                        max_digits=3,
                        verbose_name="Note",
                    ),
                ),
                (
                    "commentaires",
                    models.TextField(blank=True, verbose_name="Commentaires"),
                ),
                (
                    "evaluateur_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name="Identifiant de l'évaluateur",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="rh.employe",
                        verbose_name="Employé évalué",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "db_table": "rh_evaluation",
                "ordering": ["-date_evaluation"],
            },
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "horodatage",
                    models.DateTimeField(verbose_name="Date et heure du pointage"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ENTRY", "Entrée"), ("EXIT", "Sortie")],
                        max_length=5,
                        verbose_name="Type de pointage",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="rh.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage",
                "verbose_name_plural": "Pointages",
                "db_table": "rh_pointage",
                "ordering": ["-horodatage"],
                "indexes": [
                    models.Index(
                        fields=["employe", "horodatage"],
                        name="rh_pointage_employe_62a441_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pointage",
            constraint=models.UniqueConstraint(
                fields=("employe", "horodatage", "type"),
                name="unique_pointage_employe_horodatage_type",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluation",
            index=models.Index(
                fields=["employe", "date_evaluation"],
                name="rh_evaluati_employe_15b38d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluation",
            constraint=models.CheckConstraint(
                check=models.Q(("note__gte", 0), ("note__lte", 10)),
                name="note_entre_0_et_10",
            ),
        ),
        migrations.AddIndex(
            model_name="employe",
            index=models.Index(
                fields=["matricule"], name="rh_employe_matricu_966fc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employe",
            index=models.Index(
                fields=["agence", "est_actif"], name="rh_employe_agence__ff8aef_idx"
            ),
        ),
    ]
