# Generated by Django 4.2.30 on 2026-06-09 09:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matricule", models.CharField(max_length=10, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_embauche", models.DateField()),
                ("taux_horaire", models.DecimalField(decimal_places=2, max_digits=8)),
                ("poste", models.CharField(max_length=100)),
                ("est_actif", models.BooleanField(default=True)),
                ("role_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "rh_employe",
            },
        ),
        migrations.CreateModel(
            name="RoleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
                ("permissions", models.JSONField(default=list)),
            ],
            options={
                "db_table": "rh_role",
            },
        ),
        migrations.CreateModel(
            name="PointageModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("horodatage", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("ENTRY", "Entrée"), ("EXIT", "Sortie")], max_length=5
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.employemodel",
                    ),
                ),
            ],
            options={
                "db_table": "rh_pointage",
            },
        ),
        migrations.CreateModel(
            name="EvaluationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_evaluation", models.DateField()),
                ("note", models.DecimalField(decimal_places=1, max_digits=3)),
                ("commentaires", models.TextField(blank=True)),
                ("evaluateur_id", models.UUIDField(blank=True, null=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.employemodel",
                    ),
                ),
            ],
            options={
                "db_table": "rh_evaluation",
            },
        ),
    ]
