# Generated by Django 4.2.30 on 2026-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employemodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
