from abc import ABC, abstractmethod
from typing import Optional, List
from uuid import UUID
from datetime import date
from stock.domain.entities.bien import Bien, EtatBien
from stock.domain.value_objects.reference_bien import ReferenceBien

class BienRepository(ABC):
    @abstractmethod
    def get(self, id: UUID) -> Optional[Bien]: ...
    @abstractmethod
    def get_by_reference(self, ref: ReferenceBien) -> Optional[Bien]: ...
    @abstractmethod
    def add(self, bien: Bien) -> None: ...
    @abstractmethod
    def remove(self, bien: Bien) -> None: ...
    @abstractmethod
    def find_by_etat(self, etat: EtatBien) -> List[Bien]: ...
    @abstractmethod
    def find_disponibles_periode(self, debut: date, fin: date) -> List[Bien]: ...
    @abstractmethod
    def find_all(self) -> List[Bien]: ...