# Generated by Django 4.2.30 on 2026-06-09 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgenceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("adresse_ligne1", models.CharField(max_length=255)),
                (
                    "adresse_ligne2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("code_postal", models.CharField(max_length=20)),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(default="France", max_length=100)),
                ("telephone", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "admin_agence",
            },
        ),
        migrations.CreateModel(
            name="ModuleConfigModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("ordre_affichage", models.IntegerField(default=0)),
                ("parametres", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "admin_module_config",
            },
        ),
    ]
