# Generated by Django 4.2.30 on 2026-06-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencemodel",
            name="code",
            field=models.CharField(default="DEFAULT", max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
