# Generated by Django 4.2.30 on 2026-06-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_agencemodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencemodel",
            name="pays",
            field=models.CharField(default="RDC", max_length=100),
        ),
    ]
