# Generated by Django 4.2.30 on 2026-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_alter_agencemodel_pays"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleconfigmodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
