# Generated by Django 4.2.30 on 2026-08-14 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(max_length=30, verbose_name="Téléphone"),
                ),
                ("adresse", models.TextField(verbose_name="Adresse")),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients_location",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "location_client",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="RegleTarification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("forfait", "forfait"),
                            ("remise", "remise"),
                            ("majoration", "majoration"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valeur"
                    ),
                ),
                ("duree_min", models.PositiveIntegerField(verbose_name="Durée min")),
                (
                    "duree_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée max"
                    ),
                ),
                (
                    "bien_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="ID du bien cible",
                    ),
                ),
                (
                    "categorie_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="ID de la catégorie cible",
                    ),
                ),
                (
                    "periode_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Période début"
                    ),
                ),
                (
                    "periode_fin",
                    models.DateField(blank=True, null=True, verbose_name="Période fin"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regles_location",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de tarification",
                "verbose_name_plural": "Règles de tarification",
                "db_table": "location_regle_tarification",
                "ordering": ["periode_debut"],
            },
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bien_id",
                    models.UUIDField(verbose_name="ID du bien (référence externe)"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant total"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="actif",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrats_location",
                        to="administration.agencemodel",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="location.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "db_table": "location_contrat",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.AddConstraint(
            model_name="regletarification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("bien_id__isnull", True), ("categorie_id__isnull", True)),
                    models.Q(
                        ("bien_id__isnull", False), ("categorie_id__isnull", True)
                    ),
                    models.Q(
                        ("bien_id__isnull", True), ("categorie_id__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="either_bien_or_categorie",
            ),
        ),
    ]
