# Generated by Django 4.2.30 on 2026-06-21 21:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=30)),
                ("adresse", models.TextField()),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "location_client",
            },
        ),
        migrations.CreateModel(
            name="ContratModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bien_id", models.UUIDField()),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="actif",
                        max_length=10,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="location.clientmodel",
                    ),
                ),
            ],
            options={
                "db_table": "location_contrat",
            },
        ),
    ]
