# Generated by Django 4.2.30 on 2026-06-22 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegleTarificationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agence_id", models.UUIDField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("forfait", "Forfait"),
                            ("remise", "Remise"),
                            ("majoration", "Majoration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=12)),
                ("duree_min", models.PositiveIntegerField()),
                ("duree_max", models.PositiveIntegerField(blank=True, null=True)),
                ("type_bien_id", models.UUIDField(blank=True, null=True)),
                ("periode_debut", models.DateField(blank=True, null=True)),
                ("periode_fin", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "location_regle_tarification",
            },
        ),
    ]
