# Generated by Django 4.2.30 on 2026-06-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_regletarificationmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regletarificationmodel",
            name="type_bien_id",
        ),
        migrations.AddField(
            model_name="regletarificationmodel",
            name="bien_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="regletarificationmodel",
            name="categorie_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="regletarificationmodel",
            name="agence_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="regletarificationmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("forfait", "forfait"),
                    ("remise", "remise"),
                    ("majoration", "majoration"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="regletarificationmodel",
            name="valeur",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name="regletarificationmodel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("bien_id__isnull", True), ("categorie_id__isnull", True)),
                    models.Q(
                        ("bien_id__isnull", False), ("categorie_id__isnull", True)
                    ),
                    models.Q(
                        ("bien_id__isnull", True), ("categorie_id__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="either_bien_or_categorie",
            ),
        ),
    ]
