# Generated by Django 4.2.30 on 2026-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_remove_regletarificationmodel_type_bien_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="contratmodel",
            name="agence_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
